[2023-09-27 04:54:40,556] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:54:49,911] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.3:5000 (Press CTRL+C to quit) - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:54:49,914] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:54:54,939] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:54:54] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:54:55,047] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:54:55] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:54:55,196] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:54:55] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:54:55,298] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:54:55] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:54:56,386] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:54:56] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:54:56,405] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:54:56] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:54:56,641] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:54:56] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:54:56,712] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:54:56] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:54:57,166] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:54:57] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:55:04,983] WARNING update_pessoa() L165  Erro ao adicionar pessoa 'João Neto', Não foi possível salvar novo item :/ - call_trace=C:\Users\fadami\Desktop\pucBackEndAvançado\app.py L165 
[2023-09-27 04:55:04,991] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:55:04] "[31m[1mPUT /pessoas HTTP/1.1[0m" 400 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:55:05,944] WARNING update_pessoa() L165  Erro ao adicionar pessoa 'João Neto', Não foi possível salvar novo item :/ - call_trace=C:\Users\fadami\Desktop\pucBackEndAvançado\app.py L165 
[2023-09-27 04:55:05,946] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:55:05] "[31m[1mPUT /pessoas HTTP/1.1[0m" 400 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:55:30,428] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:55:30] "POST /pessoa HTTP/1.1" 200 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:55:31,380] WARNING add_pessoa() L123  Erro ao adicionar pessoa 'João Neto', Pessoa de mesmo nome já salvo na base :/ - call_trace=C:\Users\fadami\Desktop\pucBackEndAvançado\app.py L123 
[2023-09-27 04:55:31,381] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:55:31] "[31m[1mPOST /pessoa HTTP/1.1[0m" 409 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:55:38,644] WARNING update_pessoa() L165  Erro ao adicionar pessoa 'João Neto', Não foi possível salvar novo item :/ - call_trace=C:\Users\fadami\Desktop\pucBackEndAvançado\app.py L165 
[2023-09-27 04:55:38,646] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:55:38] "[31m[1mPUT /pessoas HTTP/1.1[0m" 400 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:55:39,215] WARNING update_pessoa() L165  Erro ao adicionar pessoa 'João Neto', Não foi possível salvar novo item :/ - call_trace=C:\Users\fadami\Desktop\pucBackEndAvançado\app.py L165 
[2023-09-27 04:55:39,217] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:55:39] "[31m[1mPUT /pessoas HTTP/1.1[0m" 400 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:58:08,794] INFO _log() L224   * Detected change in 'C:\\Users\\fadami\\Desktop\\pucBackEndAvançado\\app.py', reloading - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:58:08,981] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:58:15,615] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.3:5000 (Press CTRL+C to quit) - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:58:15,618] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:58:19,527] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:58:19] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:58:19,629] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:58:19] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:58:19,772] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:58:19] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:58:19,873] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:58:19] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:58:20,975] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:58:20] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:58:20,994] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:58:20] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:58:21,223] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:58:21] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:58:21,305] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:58:21] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:58:21,741] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:58:21] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:58:35,388] WARNING update_pessoa() L165  Erro ao adicionar pessoa 'João Neto', Não foi possível salvar novo item :/ - call_trace=C:\Users\fadami\Desktop\pucBackEndAvançado\app.py L165 
[2023-09-27 04:58:35,395] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:58:35] "[31m[1mPUT /pessoas HTTP/1.1[0m" 400 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:58:36,492] WARNING update_pessoa() L165  Erro ao adicionar pessoa 'João Neto', Não foi possível salvar novo item :/ - call_trace=C:\Users\fadami\Desktop\pucBackEndAvançado\app.py L165 
[2023-09-27 04:58:36,493] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 04:58:36] "[31m[1mPUT /pessoas HTTP/1.1[0m" 400 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:58:37,488] WARNING update_pessoa() L165  Erro ao adicionar pessoa 'João Neto', Não foi possível salvar novo item :/ - call_trace=C:\Users\fadami\Desktop\pucBackEndAvançado\app.py L165 
